theme: jekyll-theme-dinky
title: Open GIScience
description: Joseph Holler's Open GIScience Curriculum at Middlebury College
collections:
  lessons:
    output: true
timezone: America/New_York
future: true
